### ISSUE TITLE
2.1.20 breakage

### ISSUE THREAD

**Issue by rathsky** [krassowski/Anki-Night-Mode#101]
At least two new breakages coming with 2.1.20:

* After ["add more hooks, tweak wording for consistency"](https://github.com/ankitects/anki/commit/84c17e1f022b274162c8495f474565ca2a6e7f08), night_mode CSS is no longer applied to the reviewer.

* After the ["basic night mode support"](https://github.com/ankitects/anki/commit/7dcbc7efec08ec2928523408dd9bc7bdaae03fd8) (it's just black for the gui, everything the same otherwise) theming rewrite, the plugin breaks (eg., the new ThemeManager class replaces eg. previously hard-coded COLOUR_* in browser.py).

**Comment by lovac42** [comment]
Beta5 will make nm obsolete. Not sure anyone will put any more time into this.

![image](https://user-images.githubusercontent.com/42665127/73070597-b1528c80-3e7e-11ea-92c2-edecfd3b75d0.png)

![image](https://user-images.githubusercontent.com/42665127/73070635-c29b9900-3e7e-11ea-952f-c9e50fd33ec1.png)

![image](https://user-images.githubusercontent.com/42665127/73070582-aa2b7e80-3e7e-11ea-983b-22f7495f9736.png)

**Comment by rathsky** [comment]
Ah, I see. It does observe CSS now, but went with nightMode, rather than AnkiDroid's night_mode. That's… inconvenient.

Really wish he'd have adopted this addon's theming, it's much better.

**Comment by krassowski** [comment]
I think that if you ask the Anki author to consider adding `.night_mode` class, there should not be any problems (right now it is good that the two-class differ so that add-on and the built-in mode do not crash. After 2.1.20 this add-on will likely become deprecated so then there won't be a need for separate classes).

I had a look at the new Night Mode - it's not perfect yet, but it is a huge step in the right direction. Maybe not with 2.1.20, but certainly soon after (once all the features currently provided by the add-on are in the Anki core) I will rename the add-on to "Alternative/Legacy Night Mode" so that the users do not get confused.

**Comment by krassowski** [comment]
I am archiving this repository for now to avoid user confusion. Please reach out to me (Tweeter/LinkedIn/E-mail) if you want to port features of this addon to the newer versions.
