### ISSUE TITLE
"Enable in Dialogs" Hides Browser Tag Tree

### ISSUE THREAD

**Issue by bwhurd** [krassowski/Anki-Night-Mode#23]
So, this is really weird.   I've tried reinstalling anki.   Problem persists.  Using 2.0.47 on windows.  If I disable all plugins except night mode, the problem persists.  If I remove only night mode the problem goes away (with or without other plugins).

**The problem:**  If I "enable in dialogs", when the browser window comes up, the "tree" with decks/tags/etc in left hand column is very thin so can't really see anything.  If I click to drag the column wider, the column disappears altogether.  Anybody know what I'm missing?  I've tried changing monitor resolution, etc.

**Screenshots:**
**If I disable "enable in dialogs", it appears as expected:** ![image](https://user-images.githubusercontent.com/19847413/30231755-fc13c7e4-94b1-11e7-881d-d9b9c89f57c8.png)

**If I ENABLE "enable in dialogs" this is what happens—**
Initial Browser window:  ![image](https://user-images.githubusercontent.com/19847413/30231691-abfb7ad6-94b1-11e7-9b8c-be88aa43add2.png)
If I click on border between columns to drag: ![image](https://user-images.githubusercontent.com/19847413/30231723-cc941884-94b1-11e7-8983-8f2cdfab90c6.png)
after clicking to drag to expand:  ![image](https://user-images.githubusercontent.com/19847413/30231740-dd50ec4c-94b1-11e7-9eef-0b93d9197352.png)

**Comment by krassowski** [comment]
Sounds serious. Had no chance to test it on Windows yet, but tried to reproduce on Wine, without success. You use Windows 10, right? What version of Qt/PyQt (you will find these in Help->About menu in Anki)? Could you try to test it with Anki 2.1 beta 13?

**Comment by krassowski** [comment]
Also reported on reddit, though without any of useful details: https://www.reddit.com/r/Anki/comments/78cnja/what_the_f_is_wrong_with_my_left_window_browse_ui/

**Comment by KevAU** [comment]
Thanks for reply (and for the great little add-on).
I'm using the latest non-beta (2.0.48) since I'm always vary of beta's... (plus I'm a new anki user)

**Comment by krassowski** [comment]
Anyone experiencing this issue:
Could you modify NightMode.py file in your add-ons directory () and try to:
- delete https://github.com/krassowski/Anki-Night-Mode/blob/stable/2.0/Night_Mode.py#L901 line, restart Anki and verify whether the bug pertains? if not:
- delete https://github.com/krassowski/Anki-Night-Mode/blob/stable/2.0/Night_Mode.py#L870-L871, restart and verify?
- delete https://github.com/krassowski/Anki-Night-Mode/blob/stable/2.0/Night_Mode.py#L858-L861, r&v?
- delete https://github.com/krassowski/Anki-Night-Mode/blob/stable/2.0/Night_Mode.py#L821-L825, r&v?
- https://github.com/krassowski/Anki-Night-Mode/blob/stable/2.0/Night_Mode.py#L918-L933, r&v?

**Comment by bwhurd** [comment]
I initially reported this issue and if my memory serves me correct, it went away after completely reinstalling anki and clearing cache and rebooting.   If it happens again, I'll come back to this thread to troubleshoot.  Sorry I don't remember exactly what happened last time to resolve.

**Comment by krassowski** [comment]
If the problem shows up again, the solution which worked for me is to use `Ctrl+Shift+R` which is a built-in shortcut to show sidebar.

Also, I did not find anything damning this add-on - I mean it does not invoke any function which hides the sidebar directly. One possibility is that sometimes when reloading the GUI after enabling / disabling the Night Mode the sidebar fails to load and it needs to be manually invoked with `Ctrl+Shift+R` or from top bar menu in browser: Go → Sidebar.

The function itself is somehow suspected, as there is no way user could hide the sidebar - only to show it; maybe it was happening randomly before and that's way this shortcut was introduced in the first place? Then, the reports of the add-on causing this would be explained as the result of increased number of operations (every toggle of night mode require resetting most of the GUI), and therefore increased probability of the event of hiding the sidebar occurring at least once...

**Comment by chartokai** [comment]
I get the same issue on both 2.0.47 and 2.1.1 (Window's 10, Qt 5.9.6 PyQt 5.9.2) except my sidebar doesn't "disappear altogether" since the Anki upgrade. 

In the "Choose what to style" option, I have narrowed it down to only happening when "Editor" and/or "Browser" are ticked. (presumably "Browser" activates other options when in the browser window making "Editor" the culprit)

I would describe it to be as if the 'card list' has a css width: of about half the screen (1080p) forcing the sidebar to be as small as possible when the browser isn't taking up more then this width.

**Comment by krassowski** [comment]
Thank you @chartokai. Feedback like that is crucial for debugging such issues.
I assume that Ctrl+Shift+R did not work for you, did it?

**Comment by chartokai** [comment]
I tried Ctrl+Shift+R (and toggling the sidebar on and off). The attempt at resizing the sidebar may have updated its position to be off-screen, rather than removing it. It doesn't dissapear on Anki 2.1 (or at least for me as I said).

I tried removing the lines of code you said above with no luck. Although my local addon's structure is different from the old links, I found their equivalents with notepad++.

1) Got rid of the purple down arrow icon
2) I presume refers to (border:1px solid """ + self.config.color_s + """) and had no noticeable change
3) Changed the card list styles
4) No noticeable change
5) Removed most of the sidebar styles

I won't be able to respond until tomorrow now as it's late here.

**Comment by chartokai** [comment]
I tried a compleat uninstall and reinstall (including deleting C:\Users\Name\AppData\Roaming\Anki2) that worked. At the very least, it looks like a consistent way to fix it.

**Comment by omega3** [comment]
Is this solution valid for Anki 2.1 version of night-mode? I see blob/stable/2.0 here.

Looks like I have this issue:

https://github.com/hssm/advanced-browser/issues/39

You gave me this idea to turn off both add-on and now I noticed that when both are disabled the problem doesn't occurs. Then I enabled advanced browser - still no problem. Then I enabled night-mode and problem occurred.

**Comment by omega3** [comment]
I can confirm that in Anki Version 2.1.4, Qt 5.9.2 PyQt 5.9, Night Mode 2.2.2, when I disabled "Enable in Dialogs" side menu keeps its width properly. So the bug is still present in Anki 2.1. But I don't know how to modify NightMode.py because line numbers has changed.

**Comment by Novite5** [comment]
Same problem on archlinux, when both NightMode and Advanced Browser are enabled.

**Comment by stnk8** [comment]
I have the same problem as well, both in 2.0 and 2.1.  2.0 the sidebar disappears when trying to resize, but in 2.1 it doesnt. It just stays thin.   Only thing that fixes it for me is unchecking the enable in dialogues.

**Comment by Cubicle13** [comment]
I'm on 2.1.15 and I notice that the problem goes away when I switch users
Who else has solved it though doing this?

**Comment by lovac42** [comment]
This fixed it for me on windows. I had to disable the style for the search bar though.

For 2.1.15-20, if anyone wants to test it on other platforms:
[night_mode_t2_fix_no23.ankiaddon.zip](https://github.com/krassowski/Anki-Night-Mode/files/4096490/night_mode_t2_fix_no23.ankiaddon.zip)

#49 #68 #97

**Comment by AnKingMed** [comment]
It seems to be working for me so far. (I was previously user Stnk8).  I've attached an image of the only issues I'm seeing now. It plays nicer with fastbar on mac now (previously it was really ugly), but still doesn't make it night mode.  The search bar is not in nightmode and when I add a tag, and the suggestion dialog that comes up is all black.  I can submit those as separate bug reports if you want. Seems like the sidebar issue went away for me but only time will tell if it comes back

![Screen Shot 2020-01-22 at 9 22 09 AM](https://user-images.githubusercontent.com/57678116/72912608-1da38380-3cf9-11ea-9060-0b5167aa3092.jpg)

**Comment by lovac42** [comment]
This is quite the interesting little bugger. The problem turns out to be caused by extra long string in the search histories. When the dark theme stylesheet is applied, the adj size policy gets reset. This cause the sidebars to be stuck for long text strings.

Ideally the search should clear after 30 searches, but anki uses `history = history[:30]` instead of `del history[30:]` to truncate the history logs. This keeps the oldest 30th searches. So if your long text is the 31st, this problem will come and go. But if it was within the top 30th, it'll be stuck forever. Switching profile helps, until you do another long text search.

I have a personal backported version of nm2 for 2.0. Applying this fix also fixes the oldest issue from 2017 for webkit.

**Comment by AnKingMed** [comment]
So does your version fix this then?  Is there a way to restyle the search bar in the future? Thanks for your work on this! It has been a problem for me for over a year now

**Comment by lovac42** [comment]
It's fixed, but gotta wait for krassowski to make time and look over everything.

**Comment by AnKingMed** [comment]
Just as an FYI, Damien just pushed a full official nightmode in Anki 2.1.20beta5
