### ISSUE TITLE
Colour of tags unreadable

### ISSUE THREAD

**Issue by baimi1** [krassowski/Anki-Night-Mode#56]
<img width="268" alt="screen shot 2018-12-20 at 12 37 03 pm" src="https://user-images.githubusercontent.com/35539878/50384405-4d034d80-06ff-11e9-895d-4e1197c36105.png">
List of add ons: https://imgur.com/a/q2ejgQc
MacOS High Sierra, Anki Version 2.1.6. Night Mode Version 2.2.3

**Comment by krassowski** [comment]
Hi @baimi1, I would appreciate if you could fill out [the issue template](https://github.com/krassowski/Anki-Night-Mode/blob/a127d60493dae9bad55830421cf7735d13e6f701/ISSUE_TEMPLATE.md) instead of replacing it with your custom report. It was created for a reason - specifically because it is known that add-ons often interfere with each other and volunteers who create them and support users don't have time to try out combinations of dozens of add-ons that others use to discover where the conflict lies.

The picture you've posted suggests that it is the case where tags were modified by another add-on.
This might relate to #45 - please see this issue and let me know if it relates to your case as well. 

Good luck with your studies!

Note: If there will be no response within a month, this issue will be closed as a duplicate of #45.
