### ISSUE TITLE
Nightmode incomplete on Decks menu bar

### ISSUE THREAD

**Issue by Masterofnothing1** [krassowski/Anki-Night-Mode#81]
#### Problem description

Nightmode does not extend to the horizontal row including the "Decks  Add  Browse  Stats  Sync" menu bar.

#### Checklist

*Please put x inside brackets if following sentences apply to you:*

 - [x] I verified that I use the lastest add-on version,
 - [x] I verified that I use the lastest Anki version,
 - [x] I tried to disable other add-ons to find the culprit,
 - [x] I checked if anyone reported this problem before, as well as Known issues section on add-ons page,
 - [ ] My issue is solved when holding shift while starting Anki.
 
#### Information about your Anki Setup

<details>

*Please open Anki, go to Help → About, look-up two lines, starting with `Version:` and `Qt` and copy-paste them below:*

```
Version 2.1.5
Qt 5.9.2 PyQt 5.9
```

*Please got to Night Mode → About now and copy-paste the first line from the pop-up window below:*

```
Night Mode 2.2.4
```

*Please fill in your OS details (Linux/Mac/Windows):*

```
OS: Microsoft Windows 10 Home

```
 
 
*If you have a compatibility problem with a specific add-on or add-ons, please paste the add-on page links below:*
 - [Other add-on name](https://)
</details>

#### Backtrace (if any)

<details>

*If you had an error which resulted in producing exception with a backtrace, please paste the backtrace below:*

```python"
[paste your backtrace in here if you got any; otherwise feel free to remove this part]
```

</details>

![Anki Nightmode issue](https://user-images.githubusercontent.com/53971552/62821835-04db5300-bb49-11e9-9f31-d6b4bb1dec86.JPG)

**Comment by Masterofnothing1** [comment]
Problem went away for a day but has happened again several times since then.

**Comment by krassowski** [comment]
It sounds exactly like a problem that would be caused by another add-on trying to modify this part of the Anki application. Would you mind listing your add-ons?

**Comment by Masterofnothing1** [comment]
Thanks for the reply, my add on's are:
1) Advanced browser
2) Enhance main browser
3) Frozen fields 
4) Image occlusion enhanced
5) Night mode
6) zoom 21

I tried disabling each and re-starting anki but problem was still there.

**Comment by krassowski** [comment]
"Enhance main browser" seemed suspicious, I installed it but nope, it works ok for me. I am sorry but I do not see any obvious reason why is this randomly not working.

Let's keep this issue open and if anyone else has this problem and reports their versions and lists installed add-ons maybe we will be able to find some things in common and learn where to search for a culprit.

**Comment by ltsdw** [comment]
I have something that I think maybe it's related.

<details>

*Please open Anki, go to Help → About, look-up two lines, starting with `Version:` and `Qt` and copy-paste them below:*

```
Version 2.1.14 (7b93e985)
Qt 5.13.0 PyQt 5.13.0
```

*Please got to Night Mode → About now and copy-paste the first line from the pop-up window below:*

```
Night Mode 2.2.4
```

*Please fill in your OS details (Linux/Mac/Windows):*

```
OS: Arch Linux x86_64
```
</details>

Let's see:

![Captura de tela de 2019-09-05 13-22-31](https://user-images.githubusercontent.com/44977415/64360833-a2f3f900-cfe1-11e9-8edc-6d8fa609351e.png)

My add-ons:

```
Kanji Grid
Night Mode
Zoom 21
review_beatmap
```

Also tried reinstalling, but this was... idk... maybe 3-4 months ago, it's been a while since I've had this problem. I also tried to downgrade some packages at the time (I'll not remember exactly what packages though, but, idk, anki, qt things, python things... because this happened after upgraded somethings. Nothing worked)

**Comment by ltsdw** [comment]
Well... it looks like it was fixed, anki version:
<pre>
<code>
Version 2.1.16 (dev)
Qt 5.13.2 PyQt 5.13.2
</code>
</pre>

![Captura de tela de 2019-11-22 04-22-05](https://user-images.githubusercontent.com/44977415/69405946-b6108e00-0cdf-11ea-8fad-fa81e243ef6a.png)

**Comment by Masterofnothing1** [comment]
Fixed in update.
